name: Sync NoMalwares.conf

on:
  workflow_dispatch: {}
  schedule:
    # 每天 UTC 23:00 -> UTC+8 07:00
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync IP rules
        shell: bash
        env:
          SRC_URL: https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/refs/heads/master/List/ip/reject.conf
          TARGET_FILE: filters/NoMalwares.conf
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$TARGET_FILE")"
          tmpdir="$(mktemp -d)"

          echo "==> Fetch remote rules"
          curl -fsSL "$SRC_URL" -o "$tmpdir/remote.conf"

          echo "==> Extract remote lines starting with ip-cidr/ip-asn (case-insensitive), and canonicalize prefix to UPPERCASE"
          awk 'BEGIN{IGNORECASE=1}
               /^[[:space:]]*ip-(cidr|asn)/{
                 # 把行首前缀 ip-cidr / ip-asn （含后面紧随的逗号等）转成大写
                 match($0,/^[[:space:]]*ip-(cidr|asn)/)
                 pre=substr($0,RSTART,RLENGTH)
                 up=toupper(pre)
                 print up substr($0, RSTART+RLENGTH)
                 next
               }' "$tmpdir/remote.conf" \
            | sed 's/^[[:space:]]*//' \
            | LC_ALL=C sort -u > "$tmpdir/remote.upper.list"

          echo "==> Prepare local file (if missing, treat as empty)"
          touch "$TARGET_FILE"

          echo "==> Split local into three parts: uppercase-managed / lowercase-ignored / others"
          # 本地用于对比的仅限大写前缀
          LC_ALL=C grep -E '^[[:space:]]*(IP-CIDR|IP-ASN)\b' "$TARGET_FILE" \
            | sed 's/^[[:space:]]*//' \
            | LC_ALL=C sort -u > "$tmpdir/local.upper.list" || true

          # 其余内容（保留顺序；其中包含小写 ip-cidr/ip-asn 以及非 IP 规则）
          # 注意：这里仅移除大写行，保留小写与其它
          awk '!/^[[:space:]]*(IP-CIDR|IP-ASN)\b/' "$TARGET_FILE" > "$tmpdir/local.nonupper.keep"

          echo "==> Compute additions/removals (set diff on uppercase-managed lines)"
          # to_add = remote - local
          comm -13 "$tmpdir/local.upper.list" "$tmpdir/remote.upper.list" > "$tmpdir/to_add.list" || true
          # to_remove = local - remote
          comm -23 "$tmpdir/local.upper.list" "$tmpdir/remote.upper.list" > "$tmpdir/to_remove.list" || true

          echo "==> Build new uppercase-managed block to exactly match remote (local lowercase untouched)"
          cp "$tmpdir/remote.upper.list" "$tmpdir/new.upper.block"

          echo "==> Assemble new file"
          {
            cat "$tmpdir/local.nonupper.keep"
            echo
            echo "# ===== Managed by GitHub Action: UPPERCASE IP-CIDR / IP-ASN begin ====="
            cat "$tmpdir/new.upper.block"
            echo "# ===== Managed by GitHub Action: UPPERCASE IP-CIDR / IP-ASN end ====="
          } > "$tmpdir/new.NoMalwares.conf"

          if ! diff -q "$TARGET_FILE" "$tmpdir/new.NoMalwares.conf" >/dev/null; then
            echo "==> Changes detected"
            mv "$tmpdir/new.NoMalwares.conf" "$TARGET_FILE"
            echo
            echo "Added (uppercase):"
            cat "$tmpdir/to_add.list" || true
            echo
            echo "Removed (uppercase):"
            cat "$tmpdir/to_remove.list" || true
          else
            echo "==> No changes"
          fi

          echo "==> Cleanup temp"
          rm -rf "$tmpdir"

      - name: Commit & push if changed
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add filters/NoMalwares.conf
            git commit -m "chore: sync NoMalwares.conf (uppercase IP-CIDR/IP-ASN) from SKK ruleset"
            git push
          else
            echo "Nothing to commit."
          fi