name: Sync NoMalwares.conf

on:
  workflow_dispatch: {}
  schedule:
    # UTC 23:00 = UTC+8 07:00
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync IP rules
        shell: bash
        env:
          SRC_URL: https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/refs/heads/master/List/ip/reject.conf
          TARGET_FILE: filters/NoMalwares.conf
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$TARGET_FILE")"
          tmpdir="$(mktemp -d)"

          echo "==> Fetch remote rules"
          curl -fsSL "$SRC_URL" -o "$tmpdir/remote.conf"

          echo "==> Extract & normalize remote (UPPERCASE, strip no-resolve, append ,NoMalwares)"
          awk 'BEGIN{IGNORECASE=1}
               /^[[:space:]]*ip-(cidr|asn)/ {
                 n=split($0, a, ",")
                 pre=toupper(a[1])                 # IP-CIDR / IP-ASN
                 body=a[2]; gsub(/[[:space:]]+/, "", body)
                 print pre "," body ",NoMalwares"
               }' "$tmpdir/remote.conf" \
            | sed 's/,[[:space:]]*no-resolve//Ig' \
            | sed 's/^[[:space:]]*//' \
            | LC_ALL=C sort -u > "$tmpdir/remote.norm.list"

          echo "==> Prepare local file (if missing)"
          touch "$TARGET_FILE"

          echo "==> Build LOCAL compare set (BODY from UPPERCASE lines in CURRENT file)"
          awk '/^[[:space:]]*(IP-CIDR|IP-ASN)\b/ {
                 n=split($0, a, ",")
                 body=a[2]; gsub(/[[:space:]]+/, "", body)
                 print body
               }' "$TARGET_FILE" \
            | LC_ALL=C sort -u > "$tmpdir/local.body.list" || true

          echo "==> Build REMOTE compare set (BODY)"
          awk -F',' '{body=$2; gsub(/[[:space:]]+/, "", body); print body}' "$tmpdir/remote.norm.list" \
            | LC_ALL=C sort -u > "$tmpdir/remote.body.list"

          echo "==> Diff on BODY (uppercase-only universe)"
          comm -13 "$tmpdir/local.body.list"  "$tmpdir/remote.body.list" > "$tmpdir/to_add.body"    || true
          comm -23 "$tmpdir/local.body.list"  "$tmpdir/remote.body.list" > "$tmpdir/to_remove.body" || true

          echo -e "\n\033[1;32m新增的 CIDR/ASN (BODY):\033[0m"
          [[ -s "$tmpdir/to_add.body" ]] && sed 's/^/  + /' "$tmpdir/to_add.body" || echo "  (无新增)"
          echo -e "\n\033[1;31m移除的 CIDR/ASN (BODY):\033[0m"
          [[ -s "$tmpdir/to_remove.body" ]] && sed 's/^/  - /' "$tmpdir/to_remove.body" || echo "  (无移除)"

          echo "==> Strip previous managed block completely (incl. markers)"
          # 删除旧文件中受管区块（包含 begin/end 两行）
          sed -e '/^# ===== Managed by GitHub Action: UPPERCASE IP-CIDR \/ IP-ASN begin =====$/,/^# ===== Managed by GitHub Action: UPPERCASE IP-CIDR \/ IP-ASN end =====$/d' \
              "$TARGET_FILE" > "$tmpdir/local.without_managed"

          echo "==> Keep local non-uppercase lines intact"
          # 保留小写 ip-cidr/ip-asn 与其它非大写规则
          awk '!/^[[:space:]]*(IP-CIDR|IP-ASN)\b/' "$tmpdir/local.without_managed" > "$tmpdir/local.nonupper.keep"

          echo "==> Rebuild managed uppercase block to EXACTLY match remote"
          cp "$tmpdir/remote.norm.list" "$tmpdir/new.upper.block"

          echo "==> Assemble new file"
          {
            cat "$tmpdir/local.nonupper.keep"
            echo
            echo "# ===== Managed by GitHub Action: UPPERCASE IP-CIDR / IP-ASN begin ====="
            cat "$tmpdir/new.upper.block"
            echo "# ===== Managed by GitHub Action: UPPERCASE IP-CIDR / IP-ASN end ====="
          } > "$tmpdir/new.NoMalwares.conf"

          if ! diff -q "$TARGET_FILE" "$tmpdir/new.NoMalwares.conf" >/dev/null; then
            mv "$tmpdir/new.NoMalwares.conf" "$TARGET_FILE"
            echo "==> Updated NoMalwares.conf"
          else
            echo "==> No changes"
          fi

      - name: Commit & push if changed
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add filters/NoMalwares.conf
            git commit -m "chore: sync NoMalwares.conf (uppercase-only BODY compare; strip no-resolve; append ,NoMalwares; idempotent block rewrite)"
            git push
          else
            echo "Nothing to commit."
          fi