name: Sync NoMalwares.conf

on:
  workflow_dispatch: {}
  schedule:
    # UTC 23:00 = UTC+8 07:00
    - cron: "0 23 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync IP rules
        shell: bash
        env:
          SRC_URL: https://raw.githubusercontent.com/SukkaLab/ruleset.skk.moe/refs/heads/master/List/ip/reject.conf
          TARGET_FILE: filters/NoMalwares.conf
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$TARGET_FILE")"
          tmpdir="$(mktemp -d)"

          echo "==> Fetch remote rules"
          curl -fsSL "$SRC_URL" -o "$tmpdir/remote.conf"

          echo "==> Extract & normalize remote (to uppercase, drop no-resolve, add ,NoMalwares)"
          awk 'BEGIN{IGNORECASE=1}
               /^[[:space:]]*ip-(cidr|asn)/ {
                 # 切分
                 n=split($0, a, ",")
                 pre=toupper(a[1])                 # IP-CIDR / IP-ASN
                 body=a[2]                         # 主体（CIDR/ASN）
                 gsub(/[[:space:]]+/, "", body)    # 去空白
                 # 输出规范化行（无 no-resolve，末尾加 NoMalwares）
                 print pre "," body ",NoMalwares"
               }' "$tmpdir/remote.conf" \
            | sed 's/,[[:space:]]*no-resolve//Ig' \
            | sed 's/^[[:space:]]*//' \
            | LC_ALL=C sort -u > "$tmpdir/remote.norm.list"

          echo "==> Prepare local file (if missing)"
          touch "$TARGET_FILE"

          echo "==> Keep local non-uppercase lines intact"
          awk '!/^[[:space:]]*(IP-CIDR|IP-ASN)\b/' "$TARGET_FILE" > "$tmpdir/local.nonupper.keep"

          echo "==> Build comparison sets (UPPERCASE ONLY; compare BODY ONLY)"
          # 本地：只取大写开头行，抽 body（第2段），忽略后缀（例如 NoMalwares/no-resolve等）
          awk '/^[[:space:]]*(IP-CIDR|IP-ASN)\b/ {
                 n=split($0, a, ",")
                 body=a[2]; gsub(/[[:space:]]+/, "", body)
                 print body
               }' "$TARGET_FILE" \
            | LC_ALL=C sort -u > "$tmpdir/local.body.list" || true

          # 远端：从规范化列表抽 body
          awk -F',' '{body=$2; gsub(/[[:space:]]+/, "", body); print body}' "$tmpdir/remote.norm.list" \
            | LC_ALL=C sort -u > "$tmpdir/remote.body.list"

          echo "==> Diff on BODY (uppercase-only universe)"
          comm -13 "$tmpdir/local.body.list"  "$tmpdir/remote.body.list" > "$tmpdir/to_add.body"    || true
          comm -23 "$tmpdir/local.body.list"  "$tmpdir/remote.body.list" > "$tmpdir/to_remove.body" || true

          echo "==> Rebuild managed uppercase block to EXACTLY match remote"
          # 受管区块 = 远端规范化完整行（IP-CIDR/IP-ASN,body,NoMalwares）
          cp "$tmpdir/remote.norm.list" "$tmpdir/new.upper.block"

          echo "==> Assemble new file"
          {
            cat "$tmpdir/local.nonupper.keep"
            echo
            echo "# ===== Managed by GitHub Action: UPPERCASE IP-CIDR / IP-ASN begin ====="
            cat "$tmpdir/new.upper.block"
            echo "# ===== Managed by GitHub Action: UPPERCASE IP-CIDR / IP-ASN end ====="
          } > "$tmpdir/new.NoMalwares.conf"

          if ! diff -q "$TARGET_FILE" "$tmpdir/new.NoMalwares.conf" >/dev/null; then
            mv "$tmpdir/new.NoMalwares.conf" "$TARGET_FILE"
            echo "==> Updated NoMalwares.conf"
            echo "Added (body only):";   cat "$tmpdir/to_add.body"    || true
            echo "Removed (body only):"; cat "$tmpdir/to_remove.body" || true
          else
            echo "==> No changes"
          fi

      - name: Commit & push if changed
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add filters/NoMalwares.conf
            git commit -m "chore: sync NoMalwares.conf (uppercase-only compare by BODY; strip no-resolve; append ,NoMalwares)"
            git push
          else
            echo "Nothing to commit."
          fi